# Generated by Django 5.2.17 on 2026-08-21 06:42

import django.db.models.deletion
import nursing_erp.staff_fk
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0007_carelevelchange_changed_by_emp_nursinglog_staff_emp'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('bed', '床位费'), ('nursing', '护理费'), ('meal', '餐费')], max_length=10, verbose_name='费用类型')),
                ('key', models.CharField(blank=True, default='', help_text='护理费=护理等级（自理/半护/全护/失智）；床位费/餐费留空', max_length=20, verbose_name='档位')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='床位/护理=每月；餐费=每餐', max_digits=10, verbose_name='单价(元)')),
            ],
            options={
                'verbose_name': '价目',
                'verbose_name_plural': '价目表',
                'ordering': ['fee_type', 'key'],
                'constraints': [models.UniqueConstraint(fields=('fee_type', 'key'), name='feerule_type_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='账期')),
                ('bed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='床位费')),
                ('nursing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='护理费')),
                ('meal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='餐费')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合计')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('paid', '已缴费')], default='pending', max_length=10, verbose_name='状态')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('settled_by', models.CharField(blank=True, max_length=30, verbose_name='核销人')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注（减免等）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='residents.resident', verbose_name='老人')),
                ('settled_by_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_bills', to='staff.employee', verbose_name='核销人档案')),
            ],
            options={
                'verbose_name': '应收月账单',
                'verbose_name_plural': '应收月账单',
                'ordering': ['-month', 'resident__name'],
                'indexes': [models.Index(fields=['month', 'status'], name='billing_mon_month_70cd4c_idx')],
                'unique_together': {('resident', 'month')},
            },
            bases=(nursing_erp.staff_fk.StaffFkMixin, models.Model),
        ),
    ]
