# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_fee_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feerule',
            options={'ordering': ['fee_type', 'key'], 'verbose_name': '价目表', 'verbose_name_plural': '价目表'},
        ),
    ]
