# Generated by Django 6.0.7 on 2026-08-06 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0003_residentroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('category', models.CharField(choices=[('荤菜', '荤菜'), ('素菜', '素菜'), ('主食', '主食'), ('汤', '汤'), ('小菜', '小菜'), ('饮品', '饮品')], max_length=10, verbose_name='分类')),
                ('is_available', models.BooleanField(default=True, verbose_name='可用')),
            ],
            options={
                'verbose_name': '菜品库',
                'verbose_name_plural': '菜品库',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='就餐日期')),
                ('meal_type', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐')], max_length=4, verbose_name='餐次')),
                ('special_requests', models.CharField(blank=True, max_length=200, verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('ordered', '已点餐'), ('modified', '已改餐'), ('cancelled', '已退餐'), ('preparing', '备餐中'), ('delivering', '送餐中'), ('delivered', '已送达')], default='ordered', max_length=15, verbose_name='状态')),
                ('ordered_by', models.CharField(blank=True, max_length=30, verbose_name='点餐人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(to='meals.dish', verbose_name='所选菜品')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '点餐订单',
                'verbose_name_plural': '点餐订单',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('modify', '改餐'), ('cancel', '退餐')], max_length=10, verbose_name='操作类型')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=30, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='meals.mealorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '改退餐记录',
                'verbose_name_plural': '改退餐记录',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='周一日期')),
                ('day', models.CharField(choices=[('周一', '周一'), ('周二', '周二'), ('周三', '周三'), ('周四', '周四'), ('周五', '周五'), ('周六', '周六'), ('周日', '周日')], max_length=4, verbose_name='星期')),
                ('meal_type', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐')], max_length=4, verbose_name='餐次')),
                ('dishes', models.ManyToManyField(to='meals.dish', verbose_name='菜品')),
            ],
            options={
                'verbose_name': '周菜单',
                'verbose_name_plural': '周菜单',
                'ordering': ['week_start', 'day', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='月份')),
                ('total_meals', models.IntegerField(default=0, verbose_name='点餐总数')),
                ('cancelled', models.IntegerField(default=0, verbose_name='退餐次数')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收餐费')),
                ('paid', models.BooleanField(default=False, verbose_name='已缴纳')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_finances', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '餐费月结',
                'verbose_name_plural': '餐费月结',
                'ordering': ['-month', 'resident__name'],
                'unique_together': {('resident', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['date', 'status'], name='meals_mealo_date_71c627_idx'),
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['resident', 'date'], name='meals_mealo_residen_c72b71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weekmenu',
            unique_together={('week_start', 'day', 'meal_type')},
        ),
    ]
