# Generated by Django 6.0.7 on 2026-08-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0003_residentroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='就餐日期')),
                ('meal_type', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐')], max_length=4, verbose_name='餐次')),
                ('menu_choice', models.TextField(verbose_name='所选菜品')),
                ('special_requests', models.TextField(blank=True, verbose_name='特殊要求')),
                ('status', models.CharField(choices=[('ordered', '已点餐'), ('modified', '已改餐'), ('cancelled', '已退餐'), ('preparing', '备餐中'), ('delivering', '送餐中'), ('delivered', '已送达')], default='ordered', max_length=15, verbose_name='状态')),
                ('ordered_by', models.CharField(blank=True, max_length=30, verbose_name='点餐人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '点餐订单',
                'verbose_name_plural': '点餐订单',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('modify', '改餐'), ('cancel', '退餐')], max_length=10, verbose_name='操作类型')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=30, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='meals.mealorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '改退餐记录',
                'verbose_name_plural': '改退餐记录',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('meal_type', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐')], max_length=4, verbose_name='餐次')),
                ('menu_items', models.TextField(verbose_name='菜品')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['date', 'meal_type'],
                'unique_together': {('date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='月份')),
                ('total_meals', models.IntegerField(default=0, verbose_name='点餐总数')),
                ('cancelled', models.IntegerField(default=0, verbose_name='退餐次数')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收餐费')),
                ('paid', models.BooleanField(default=False, verbose_name='已缴纳')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_finances', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '餐费月结',
                'verbose_name_plural': '餐费月结',
                'ordering': ['-month', 'resident__name'],
                'unique_together': {('resident', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['date', 'status'], name='meals_mealo_date_71c627_idx'),
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['resident', 'date'], name='meals_mealo_residen_c72b71_idx'),
        ),
    ]
