# Generated by Django 5.2.17 on 2026-08-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealmodificationlog',
            name='changed_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_modifications', to='staff.employee', verbose_name='操作人档案'),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='ordered_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_orders', to='staff.employee', verbose_name='点餐人档案'),
        ),
    ]
