# Generated by Django 5.2.17 on 2026-08-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealmodificationlog_changed_by_emp_and_more'),
        ('residents', '0007_carelevelchange_changed_by_emp_nursinglog_staff_emp'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mealorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('resident', 'date', 'meal_type'), name='uniq_active_meal_order_per_slot'),
        ),
    ]
