# Generated by Django 5.2.17 on 2026-08-24 06:38

import django.db.models.deletion
from django.db import migrations, models

import nursing_erp.staff_fk


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0007_carelevelchange_changed_by_emp_nursinglog_staff_emp'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevelMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], unique=True, verbose_name='能力等级')),
                ('care_level', models.CharField(choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], max_length=10, verbose_name='护理档')),
            ],
            options={
                'verbose_name': '等级映射',
                'verbose_name_plural': '等级映射表',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_date', models.DateField(verbose_name='评估日期')),
                ('assessor1', models.CharField(max_length=30, verbose_name='评估员1（医护）')),
                ('assessor2', models.CharField(max_length=30, verbose_name='评估员2')),
                ('total_score', models.PositiveSmallIntegerField(default=0, verbose_name='总分(0-100)')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=0, verbose_name='能力等级')),
                ('suggested_level', models.CharField(blank=True, choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], default='', max_length=10, verbose_name='建议护理档')),
                ('status', models.CharField(choices=[('draft', '待定级'), ('confirmed', '已定级')], default='draft', max_length=10, verbose_name='状态')),
                ('final_level', models.CharField(blank=True, choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], default='', max_length=10, verbose_name='定级结果')),
                ('confirm_reason', models.CharField(blank=True, max_length=200, verbose_name='定级说明')),
                ('confirmed_by', models.CharField(blank=True, max_length=30, verbose_name='定级人')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='定级时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor1_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_primary', to='staff.employee', verbose_name='评估员1档案')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '入住评估',
                'verbose_name_plural': '入住评估',
                'ordering': ['-assess_date', '-id'],
            },
            bases=(nursing_erp.staff_fk.StaffFkMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('自理能力', '自理能力'), ('基础运动能力', '基础运动能力'), ('精神状态', '精神状态'), ('感知觉与社会参与', '感知觉与社会参与')], max_length=10, verbose_name='一级指标')),
                ('name', models.CharField(max_length=30, verbose_name='二级指标')),
                ('max_score', models.PositiveSmallIntegerField(default=10, verbose_name='分值上限')),
                ('order', models.PositiveSmallIntegerField(verbose_name='展示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用')),
            ],
            options={
                'verbose_name': '评估项目',
                'verbose_name_plural': '评估项目目录',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('dimension', 'name'), name='item_dim_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='得分')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment', verbose_name='评估单')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_rows', to='assessments.assessmentitem', verbose_name='项目')),
            ],
            options={
                'verbose_name': '评估明细',
                'verbose_name_plural': '评估明细',
                'ordering': ['item__order'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['resident', 'status'], name='assessments_residen_8c6b57_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('assessment', 'item'), name='score_assessment_item_unique'),
        ),
    ]
