# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seed_catalog_and_grade_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevelmap',
            options={'ordering': ['grade'], 'verbose_name': '等级映射表', 'verbose_name_plural': '等级映射表'},
        ),
    ]
