# Generated by Django 6.0.7 on 2026-08-04 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('dept', models.CharField(choices=[('护理科', '护理科'), ('总务科', '总务科'), ('综合办', '综合办'), ('医务科', '医务科'), ('财务科', '财务科'), ('安保科', '安保科')], max_length=20, verbose_name='部门')),
                ('building', models.CharField(blank=True, max_length=20, verbose_name='负责楼栋')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='手机号')),
                ('is_caregiver', models.BooleanField(default=True, verbose_name='是否护理员')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
                'ordering': ['dept', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('clock_in', models.DateTimeField(verbose_name='上班打卡')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='下班打卡')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('shift', models.CharField(choices=[('白班', '白班(7-19)'), ('夜班', '夜班(19-7)')], max_length=4, verbose_name='班次')),
                ('building', models.CharField(blank=True, max_length=20, verbose_name='楼栋')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='楼层')),
                ('task_note', models.CharField(blank=True, max_length=200, verbose_name='任务备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'ordering': ['date', 'shift'],
                'indexes': [models.Index(fields=['date'], name='staff_sched_date_8927db_idx'), models.Index(fields=['building', 'date'], name='staff_sched_buildin_8043d5_idx')],
                'unique_together': {('employee', 'date', 'shift')},
            },
        ),
    ]
