# Generated by Django 6.0.7 on 2026-08-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigner_name', models.CharField(max_length=30, verbose_name='派发人')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('content', models.TextField(blank=True, verbose_name='任务内容')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='staff.employee', verbose_name='接收人')),
            ],
            options={
                'verbose_name': '任务派发',
                'verbose_name_plural': '任务派发',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='考核月份')),
                ('attendance_score', models.IntegerField(default=100, verbose_name='出勤分')),
                ('quality_score', models.IntegerField(default=100, verbose_name='工作质量分')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='staff.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '绩效考核',
                'verbose_name_plural': '绩效考核',
                'ordering': ['-month', 'employee__name'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
