# Generated by Django 6.0.7 on 2026-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('院长', '院长'), ('护理科', '护理科'), ('总务科', '总务科'), ('综合办', '综合办'), ('医务科', '医务科'), ('财务科', '财务科'), ('安全保卫科', '安全保卫科')], max_length=20, verbose_name='部门'),
        ),
    ]
