# Generated by Django 5.2.17 on 2026-08-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigner_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='staff.employee', verbose_name='派发人档案'),
        ),
    ]
