# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_seed_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'shift'], 'verbose_name': '排班表', 'verbose_name_plural': '排班表'},
        ),
    ]
