# Generated by Django 5.2.17 on 2026-08-25 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('staff', '员工'), ('family', '家属'), ('ai', 'AI 助手'), ('system', '系统')], max_length=10, verbose_name='身份')),
                ('actor_name', models.CharField(max_length=40, verbose_name='操作人')),
                ('action', models.CharField(max_length=30, verbose_name='动作')),
                ('target', models.CharField(blank=True, max_length=120, verbose_name='对象')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='对象模型')),
                ('target_id', models.CharField(blank=True, max_length=20, verbose_name='对象ID')),
                ('detail', models.TextField(blank=True, verbose_name='说明')),
                ('method', models.CharField(blank=True, max_length=8, verbose_name='方法')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='状态码')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_type', 'created_at'], name='auditlog_op_actor_t_ff8d19_idx'), models.Index(fields=['action', 'created_at'], name='auditlog_op_action_a4a612_idx')],
            },
        ),
    ]
