# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '业务操作日志', 'verbose_name_plural': '业务操作日志'},
        ),
    ]
