# Generated by Django 5.2.17 on 2026-08-24 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import family.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0008_carelevelchange_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('token', models.CharField(default=family.models._new_token, editable=False, max_length=64, unique=True, verbose_name='AI 接入令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '家属账号',
                'verbose_name_plural': '家属账号',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('子女', '子女'), ('配偶', '配偶'), ('父母', '父母'), ('兄弟姐妹', '兄弟姐妹'), ('其他', '其他')], default='子女', max_length=10, verbose_name='与老人关系')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_bindings', to='residents.resident', verbose_name='老人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='family.familymember', verbose_name='家属')),
            ],
            options={
                'verbose_name': '家属绑定',
                'verbose_name_plural': '家属绑定',
                'ordering': ['family__name', 'resident__name'],
                'constraints': [models.UniqueConstraint(fields=('family', 'resident'), name='family_resident_unique')],
            },
        ),
    ]
