# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familybinding',
            options={'ordering': ['family__name', 'resident__name'], 'verbose_name': '绑定台账', 'verbose_name_plural': '绑定台账'},
        ),
    ]
