# Generated by Django 6.0.7 on 2026-08-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(default='男', max_length=4, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('building', models.CharField(max_length=20, verbose_name='楼栋')),
                ('floor', models.CharField(max_length=10, verbose_name='楼层')),
                ('room', models.CharField(max_length=10, verbose_name='房间号')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='入住日期')),
                ('diagnosis', models.TextField(blank=True, verbose_name='既往病史')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('care_level', models.CharField(choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], default='自理', max_length=10, verbose_name='护理等级')),
                ('contact_name', models.CharField(blank=True, max_length=30, verbose_name='紧急联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '老人档案',
                'verbose_name_plural': '老人档案',
                'ordering': ['building', 'floor', 'room'],
                'indexes': [models.Index(fields=['building'], name='residents_r_buildin_722c3e_idx'), models.Index(fields=['care_level'], name='residents_r_care_le_cef31d_idx'), models.Index(fields=['name'], name='residents_r_name_ab1580_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='日期')),
                ('log_time', models.TimeField(auto_now_add=True, verbose_name='记录时间')),
                ('category', models.CharField(choices=[('feeding', '喂饭/协助进食'), ('hygiene', '洗漱/助浴'), ('toilet', '如厕协助'), ('turning', '翻身护理'), ('medicine', '服药'), ('vital_signs', '生命体征测量'), ('rehab', '康复训练'), ('other', '其他')], max_length=20, verbose_name='护理类型')),
                ('detail', models.TextField(blank=True, verbose_name='详细记录')),
                ('staff_name', models.CharField(blank=True, max_length=30, verbose_name='护理员')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '护理日志',
                'verbose_name_plural': '护理日志',
                'ordering': ['-log_date', '-log_time'],
                'indexes': [models.Index(fields=['log_date'], name='residents_n_log_dat_e7e305_idx'), models.Index(fields=['resident', 'log_date'], name='residents_n_residen_9e08d7_idx')],
            },
        ),
    ]
