# Generated by Django 6.0.7 on 2026-08-04 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='日期')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='血压')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='血糖(mmol/L)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率(次/分)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温(℃)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['resident', 'record_date'], name='residents_h_residen_6d17da_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, verbose_name='药品名称')),
                ('dosage', models.CharField(max_length=50, verbose_name='剂量')),
                ('frequency', models.CharField(choices=[('qd', '每日1次'), ('bid', '每日2次'), ('tid', '每日3次'), ('qid', '每日4次'), ('prn', '必要时')], default='qd', max_length=10, verbose_name='频次')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='服用中')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'ordering': ['-is_active', 'medicine_name'],
                'indexes': [models.Index(fields=['resident', 'is_active'], name='residents_m_residen_b0d79d_idx')],
            },
        ),
    ]
