# Generated by Django 6.0.7 on 2026-08-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_healthrecord_medicationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='日期')),
                ('wake_up', models.TimeField(blank=True, null=True, verbose_name='起床时间')),
                ('sleep', models.TimeField(blank=True, null=True, verbose_name='就寝时间')),
                ('breakfast', models.BooleanField(default=True, verbose_name='早餐')),
                ('lunch', models.BooleanField(default=True, verbose_name='午餐')),
                ('dinner', models.BooleanField(default=True, verbose_name='晚餐')),
                ('activities', models.TextField(blank=True, verbose_name='活动情况')),
                ('mood', models.CharField(blank=True, max_length=20, verbose_name='情绪状态')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '老人作息',
                'verbose_name_plural': '老人作息',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['resident', 'log_date'], name='residents_r_residen_8916d3_idx')],
            },
        ),
    ]
