# Generated by Django 6.0.7 on 2026-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_residentroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, upload_to='residents/', verbose_name='老人照片'),
        ),
    ]
