# Generated by Django 6.0.7 on 2026-08-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_resident_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLevelChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], max_length=10, verbose_name='原等级')),
                ('to_level', models.CharField(choices=[('自理', '自理'), ('半护', '半护'), ('全护', '全护'), ('失智', '失智')], max_length=10, verbose_name='新等级')),
                ('change_date', models.DateField(verbose_name='变更日期')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('changed_by', models.CharField(blank=True, max_length=30, verbose_name='经办人')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_changes', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '护理等级变更',
                'verbose_name_plural': '护理等级变更',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_type', models.CharField(choices=[('出院', '出院'), ('转院', '转院'), ('身故', '身故')], max_length=10, verbose_name='离院类型')),
                ('discharge_date', models.DateField(verbose_name='离院日期')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '离院记录',
                'verbose_name_plural': '离院记录',
                'ordering': ['-discharge_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(choices=[('自理区', '自理区'), ('介助区', '介助区'), ('介护区', '介护区'), ('认知障碍专区', '认知障碍专区')], max_length=20, verbose_name='原区域')),
                ('to_zone', models.CharField(choices=[('自理区', '自理区'), ('介助区', '介助区'), ('介护区', '介护区'), ('认知障碍专区', '认知障碍专区')], max_length=20, verbose_name='新区域')),
                ('transfer_date', models.DateField(verbose_name='转区日期')),
                ('reason', models.TextField(blank=True, verbose_name='转区原因')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '转区记录',
                'verbose_name_plural': '转区记录',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
