# Generated by Django 5.2.17 on 2026-08-21 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
        ('residents', '0005_carelevelchange_dischargerecord_transferrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='bed',
            field=models.ForeignKey(blank=True, help_text='选择床位后自动同步楼栋/楼层/房间；不一致时以床位为准', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupant', to='beds.bed', verbose_name='床位'),
        ),
        migrations.AddConstraint(
            model_name='resident',
            constraint=models.UniqueConstraint(condition=models.Q(('bed__isnull', False)), fields=('bed',), name='resident_bed_unique', violation_error_message='该床位已有老人入住'),
        ),
    ]
