# Generated by Django 5.2.17 on 2026-08-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_resident_bed_resident_resident_bed_unique'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelevelchange',
            name='changed_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_level_changes', to='staff.employee', verbose_name='经办人档案'),
        ),
        migrations.AddField(
            model_name='nursinglog',
            name='staff_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_logs', to='staff.employee', verbose_name='护理员档案'),
        ),
    ]
