# Generated by Django 5.2.17 on 2026-08-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('residents', '0007_carelevelchange_changed_by_emp_nursinglog_staff_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelevelchange',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='入住评估定级自动生成时回填；手工变更留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_changes', to='assessments.assessment', verbose_name='关联评估'),
        ),
    ]
