# Generated by Django 5.2.17 on 2026-08-26 02:07

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

# 入住记录（AdmissionRecord 代理模型）的 view 权限发放对象：
# 与 view_transferrecord / view_dischargerecord 同范围（staff.0006 GROUP_PERMS）
GRANT_GROUPS = ("护理组", "院办管理组")


def grant(apps, schema_editor):
    # post_migrate 信号在本迁移之后才跑，权限行尚不存在——先显式创建（幂等）
    create_permissions(global_apps.get_app_config("residents"))

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.get(
        content_type__app_label="residents", codename="view_admissionrecord"
    )
    for group in Group.objects.filter(name__in=GRANT_GROUPS):
        group.permissions.add(perm)  # add 而非 set：不动组内既有权限


def ungrant(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.filter(
        content_type__app_label="residents", codename="view_admissionrecord"
    ).first()
    if perm:
        for group in Group.objects.filter(name__in=GRANT_GROUPS):
            group.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_carelevelchange_assessment'),
        ('staff', '0006_seed_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
            ],
            options={
                'verbose_name': '入住记录',
                'verbose_name_plural': '入住记录',
                'ordering': ['-admission_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('residents.resident',),
        ),
        migrations.RunPython(grant, ungrant),
    ]
