# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_admissionrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carelevelchange',
            options={'ordering': ['-change_date'], 'verbose_name': '护理等级变更记录', 'verbose_name_plural': '护理等级变更记录'},
        ),
        migrations.AlterModelOptions(
            name='nursinglog',
            options={'ordering': ['-log_date', '-log_time'], 'verbose_name': '护理记录', 'verbose_name_plural': '护理记录'},
        ),
        migrations.AlterModelOptions(
            name='residentroutine',
            options={'ordering': ['-log_date'], 'verbose_name': '作息记录', 'verbose_name_plural': '作息记录'},
        ),
    ]
