# Generated by Django 5.2.17 on 2026-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_alter_carelevelchange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别'),
        ),
    ]
