# Generated by Django 5.2.17 on 2026-08-21 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='须与员工档案的楼栋名一致（如 1号楼），改名会导致楼栋权限失配', max_length=20, unique=True, verbose_name='楼栋名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='楼层名称')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='beds.building', verbose_name='楼栋')),
            ],
            options={
                'verbose_name': '楼层',
                'verbose_name_plural': '楼层',
                'ordering': ['building__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='房间号')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='beds.floor', verbose_name='楼层')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['floor__building__name', 'floor__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='床位号')),
                ('status', models.CharField(choices=[('可用', '可用'), ('维修', '维修'), ('停用', '停用')], default='可用', max_length=10, verbose_name='床位状态')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='beds.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '床位',
                'verbose_name_plural': '床位',
                'ordering': ['room__floor__building__name', 'room__floor__name', 'room__number', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='uniq_floor_per_building'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='uniq_room_per_floor'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status'], name='beds_bed_status_afe91f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'number'), name='uniq_bed_per_room'),
        ),
    ]
