# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['room__floor__building__name', 'room__floor__name', 'room__number', 'number'], 'verbose_name': '床位台账', 'verbose_name_plural': '床位台账'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': '楼栋台账', 'verbose_name_plural': '楼栋台账'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building__name', 'name'], 'verbose_name': '楼层台账', 'verbose_name_plural': '楼层台账'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__building__name', 'floor__name', 'number'], 'verbose_name': '房间台账', 'verbose_name_plural': '房间台账'},
        ),
    ]
