# Generated by Django 6.0.7 on 2026-08-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=30, verbose_name='申请人')),
                ('approval_type', models.CharField(choices=[('leave', '请假'), ('purchase', '采购'), ('reimburse', '报销'), ('other', '其他')], max_length=10, verbose_name='审批类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='申请内容')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '审批单',
                'verbose_name_plural': '审批单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(max_length=30, verbose_name='巡检人')),
                ('area', models.CharField(max_length=100, verbose_name='巡检区域')),
                ('date', models.DateField(verbose_name='巡检日期')),
                ('result', models.CharField(choices=[('合格', '合格'), ('不合格', '不合格')], max_length=4, verbose_name='巡检结果')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '卫生巡检',
                'verbose_name_plural': '卫生巡检',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('category', models.CharField(choices=[('护理耗材', '护理耗材'), ('医疗器械', '医疗器械'), ('防护用品', '防护用品'), ('清洁消毒', '清洁消毒'), ('辅助器具', '辅助器具')], max_length=10, verbose_name='分类')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
            ],
            options={
                'verbose_name': '库存物品',
                'verbose_name_plural': '库存物品',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(max_length=100, verbose_name='所在位置')),
                ('fault_description', models.TextField(verbose_name='故障描述')),
                ('reported_by', models.CharField(blank=True, max_length=30, verbose_name='报修人')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '维修中'), ('done', '已完成')], default='pending', max_length=15, verbose_name='状态')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '报修工单',
                'verbose_name_plural': '报修工单',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('date', models.DateField(verbose_name='入库日期')),
                ('operator', models.CharField(blank=True, max_length=30, verbose_name='操作人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.inventoryitem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='领用数量')),
                ('taken_by', models.CharField(blank=True, max_length=30, verbose_name='领用人')),
                ('date', models.DateField(verbose_name='领用日期')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.inventoryitem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '领用记录',
                'verbose_name_plural': '领用记录',
                'ordering': ['-date'],
            },
        ),
    ]
