# Generated by Django 5.2.17 on 2026-08-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='applicant_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='staff.employee', verbose_name='申请人档案'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='staff.employee', verbose_name='巡检人档案'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='reported_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_orders', to='staff.employee', verbose_name='报修人档案'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='operator_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='staff.employee', verbose_name='操作人档案'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='taken_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='staff.employee', verbose_name='领用人档案'),
        ),
    ]
