# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_approval_applicant_emp_inspection_inspector_emp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-created_at'], 'verbose_name': '审批流程', 'verbose_name_plural': '审批流程'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'name'], 'verbose_name': '库存台账', 'verbose_name_plural': '库存台账'},
        ),
    ]
