# Generated by Django 6.0.7 on 2026-08-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fall', '摔倒'), ('illness', '突发不适'), ('mood', '情绪异常'), ('refuse_eat', '拒食'), ('wander', '走失风险'), ('skin', '皮肤破损'), ('other', '其他')], max_length=15, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('info', '一般'), ('warning', '紧急'), ('danger', '危急')], default='info', max_length=10, verbose_name='严重程度')),
                ('description', models.TextField(blank=True, verbose_name='补充说明')),
                ('handled', models.BooleanField(default=False, verbose_name='已处理')),
                ('handled_by', models.CharField(blank=True, max_length=30, verbose_name='处理人')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='residents.resident', verbose_name='老人')),
            ],
            options={
                'verbose_name': '异常上报',
                'verbose_name_plural': '异常上报',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handled', 'severity'], name='incidents_i_handled_e70fb2_idx'), models.Index(fields=['created_at'], name='incidents_i_created_e00552_idx')],
            },
        ),
    ]
