# Generated by Django 5.2.17 on 2026-08-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('staff', '0005_task_assigner_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='handled_by_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_incidents', to='staff.employee', verbose_name='处理人档案'),
        ),
    ]
