# Generated by Django 5.2.17 on 2026-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentreport_handled_by_emp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-created_at'], 'verbose_name': '异常记录', 'verbose_name_plural': '异常记录'},
        ),
    ]
